name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    environment: Nuget-Prod
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      # Publish
      - name: Package_library
        run: dotnet pack -c Release -o . LINQPad-Interactive.Convert.Lib/LINQPad-Interactive.Convert.Lib.csproj

      - name: Package_library
        run: dotnet pack -c Release -o . Ambrose.Linqpad.Convert.KernelExt/Ambrose.Linqpad.Convert.KernelExt.csproj
        
      - name: Publish
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
